# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

 - script: dotnet build MyProject.csproj --no-restore --configuration Release
# - task: DotNetCoreCLI@2
#   displayName: 'Build the project'
#   inputs:
#     command: 'build'
#     arguments: '--no-restore --configuration Release'
#     projects: '**/*.csproj'
